"""Generate and post validation results as a GitHub PR comment."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from operations.scripts.common.project import find_project_root, read_text


def load_evidence(evidence_path: Path) -> dict:
    """Load the latest evidence bundle."""
    if not evidence_path.exists():
        return {}
    return json.loads(read_text(evidence_path))


def format_pr_comment(evidence: dict, check_summary: dict, test_returncode: int) -> str:
    """Format validation results as markdown for PR comment."""
    git_sha = evidence.get("git_sha", "unknown")[:8]
    checks = [item for item in check_summary.get("checks", []) if isinstance(item, dict)]
    passed_checks = sum(1 for item in checks if item.get("ok"))
    total_checks = len(checks)
    test_status = "✅ PASS" if test_returncode == 0 else "❌ FAIL"

    lines = [
        "## 📋 Project Validation Results",
        "",
        f"**Commit:** `{git_sha}`",
        "",
        "| Check | Status |",
        "|---|---|",
    ]

    for item in checks:
        name = item.get("name", "unknown")
        ok = item.get("ok", False)
        status = "✅" if ok else "❌"
        lines.append(f"| {name} | {status} |")

    lines.extend(
        [
            "",
            "| Category | Result |",
            "|---|---|",
            f"| Unit Tests | {test_status} |",
            f"| Document Checks | {passed_checks}/{total_checks} |",
            "",
        ]
    )

    if checks:
        errors = []
        for item in checks:
            for error in item.get("errors", []) if isinstance(item.get("errors"), list) else []:
                errors.append(f"- **{item.get('name')}**: {error}")

        if errors:
            lines.extend(
                [
                    "### Errors",
                    "",
                    *errors,
                    "",
                ]
            )

    acceptance = evidence.get("acceptance_state", "unknown")
    lines.extend(
        [
            f"**Acceptance State:** `{acceptance}`",
            "",
            "---",
            "_Generated by [Claude Code](https://claude.ai/code)_",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate PR comment from validation results")
    parser.add_argument("--evidence-path", required=True, help="Path to evidence bundle JSON")
    parser.add_argument("--check-summary", required=True, help="Path to check_summary.json")
    parser.add_argument("--test-returncode", type=int, required=True, help="Unit test return code")
    parser.add_argument("--output", required=True, help="Path to write comment markdown")
    args = parser.parse_args()

    root = find_project_root(Path.cwd())

    evidence_path = Path(args.evidence_path)
    if not evidence_path.is_absolute():
        evidence_path = root / evidence_path

    check_path = Path(args.check_summary)
    if not check_path.is_absolute():
        check_path = root / check_path

    evidence = load_evidence(evidence_path)
    check_summary = json.loads(read_text(check_path)) if check_path.exists() else {}

    comment = format_pr_comment(evidence, check_summary, args.test_returncode)

    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = root / output_path

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(comment)
    print(f"PR comment written to {output_path.relative_to(root)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
